title: Site

tabs:
  pages:
    label: Pages du site
    sections:
      contact:
        type: fields
        headline: Coordonnées de contact (global)
        fields:
          contactEmail:
            label: E-mail de contact
            type: email
            width: 1/2
            help: Adresse e-mail affichée dans le footer.
          contactPhone:
            label: Téléphone de contact
            type: tel
            width: 1/2
            help: Numéro affiché dans le footer.
      mainPages:
        type: pages
        label: Pages du site
        status: all
        create: false
        sortable: false
        templates:
          - home
          - mentions-legales
          - politique-confidentialite
